name: Flujo de trabajo de CI

# Activadores del workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      # Paso 1: Checkout del código
      - name: Checkout
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Asegúrate de instalar flake8

      # Paso 3: Lint con flake8
      - name: Lint con flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
